# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8086/senderAccount
Content-Type: application/json

{
  "id": "33ddd",
  "username": "kek",
  "password": "ggfg13"
}

###

POST http://localhost:8086/senderAccount
Content-Type: application/json

{
  "id": "2345",
  "username": "ogrezem",
  "password": "133fff"
}

###

GET http://localhost:8086/senderAccount/username/ogrezem
Content-Type: application/json

{

}

###

DELETE http://localhost:8086/senderAccount/username/babka
Content-Type: application/json

{

}

###

PUT http://localhost:8086/senderAccount/username/babka
Content-Type: application/json

{
  "id": "3553",
  "username": "babka",
  "password": "133fff"
}

###